service: email-api

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  timeout: 30 

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post

custom:
  serverless-offline:
    httpPort: 3000   
